/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account-settings-account': RouteRecordInfo<'account-settings-account', '/account-settings/account', Record<never, never>, Record<never, never>>,
    'account-settings-billing-plans': RouteRecordInfo<'account-settings-billing-plans', '/account-settings/billing-plans', Record<never, never>, Record<never, never>>,
    'account-settings-billing-history-table': RouteRecordInfo<'account-settings-billing-history-table', '/account-settings/BillingHistoryTable', Record<never, never>, Record<never, never>>,
    'account-settings-notification': RouteRecordInfo<'account-settings-notification', '/account-settings/notification', Record<never, never>, Record<never, never>>,
    'account-settings-security': RouteRecordInfo<'account-settings-security', '/account-settings/security', Record<never, never>, Record<never, never>>,
    'bots': RouteRecordInfo<'bots', '/bots', Record<never, never>, Record<never, never>>,
    'create-bot': RouteRecordInfo<'create-bot', '/create-bot', Record<never, never>, Record<never, never>>,
    'deposit': RouteRecordInfo<'deposit', '/deposit', Record<never, never>, Record<never, never>>,
    'edit-bot': RouteRecordInfo<'edit-bot', '/edit-bot', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'internal-transfer': RouteRecordInfo<'internal-transfer', '/internal-transfer', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'my-exchanges': RouteRecordInfo<'my-exchanges', '/my-exchanges', Record<never, never>, Record<never, never>>,
    'my-loyalty-points': RouteRecordInfo<'my-loyalty-points', '/my-loyalty-points', Record<never, never>, Record<never, never>>,
    'my-wallet': RouteRecordInfo<'my-wallet', '/my-wallet', Record<never, never>, Record<never, never>>,
    'onboarding-landing': RouteRecordInfo<'onboarding-landing', '/onboarding/landing', Record<never, never>, Record<never, never>>,
    'onboarding-step1': RouteRecordInfo<'onboarding-step1', '/onboarding/Step1', Record<never, never>, Record<never, never>>,
    'onboarding-step2': RouteRecordInfo<'onboarding-step2', '/onboarding/Step2', Record<never, never>, Record<never, never>>,
    'onboarding-step3': RouteRecordInfo<'onboarding-step3', '/onboarding/Step3', Record<never, never>, Record<never, never>>,
    'onboarding-step4': RouteRecordInfo<'onboarding-step4', '/onboarding/Step4', Record<never, never>, Record<never, never>>,
    'onboarding-step5': RouteRecordInfo<'onboarding-step5', '/onboarding/Step5', Record<never, never>, Record<never, never>>,
    'onboarding-verification': RouteRecordInfo<'onboarding-verification', '/onboarding/verification', Record<never, never>, Record<never, never>>,
    'onboarding-welcome': RouteRecordInfo<'onboarding-welcome', '/onboarding/welcome', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'view-bot': RouteRecordInfo<'view-bot', '/view-bot', Record<never, never>, Record<never, never>>,
    'withdraw': RouteRecordInfo<'withdraw', '/withdraw', Record<never, never>, Record<never, never>>,
  }
}
