/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'bots': RouteRecordInfo<'bots', '/bots', Record<never, never>, Record<never, never>>,
    'create-bot': RouteRecordInfo<'create-bot', '/create-bot', Record<never, never>, Record<never, never>>,
    'edit-bot': RouteRecordInfo<'edit-bot', '/edit-bot', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'onboarding-landing': RouteRecordInfo<'onboarding-landing', '/onboarding/landing', Record<never, never>, Record<never, never>>,
    'onboarding-step1': RouteRecordInfo<'onboarding-step1', '/onboarding/Step1', Record<never, never>, Record<never, never>>,
    'onboarding-step2': RouteRecordInfo<'onboarding-step2', '/onboarding/Step2', Record<never, never>, Record<never, never>>,
    'onboarding-verification': RouteRecordInfo<'onboarding-verification', '/onboarding/verification', Record<never, never>, Record<never, never>>,
    'onboarding-welcome': RouteRecordInfo<'onboarding-welcome', '/onboarding/welcome', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'view-bot': RouteRecordInfo<'view-bot', '/view-bot', Record<never, never>, Record<never, never>>,
  }
}
